export const projects = [
  {
    heading: 'Pluto',
    what: 'Finance intelligence platform for esports creators, gamers, and orgs — track revenue streams, sponsorships, and tournament earnings in one dashboard.',
    features: [
      'Multi-source revenue tracking',
      'Creator analytics',
      'Earnings dashboard',
      'Org management',
    ],
    techstack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Prisma'],
    github: 'https://github.com/parthiv011/',
    status: 'wip' as const,
  },
  {
    heading: 'Upwork Proposal Generator',
    what: 'Automated pipeline that scrapes Upwork listings and generates tailored proposals using LLMs — reducing manual effort by ~10x.',
    features: [
      '4,000+ listings/day',
      '92% scrape success rate',
      'Proposal in under 4s',
      'Editable output UI',
    ],
    techstack: ['Node.js', 'Puppeteer', 'Python', 'LangChain', 'OpenAI'],
    github: 'https://github.com/parthiv011/upwork-scraping',
    status: 'live' as const,
  },
  {
    heading: 'Astitva Notify',
    what: 'SaaS platform that delivers real-time Discord notifications for sales, signups, and payments — giving developers instant visibility into product activity.',
    features: ['Event-driven webhooks', 'Discord integration', 'Activity log', 'Stripe payments'],
    techstack: ['Next.js', 'TypeScript', 'Clerk', 'Stripe', 'Discord API', 'NeonDB'],
    github: 'https://github.com/parthiv011/saas',
    status: 'live' as const,
  },
  {
    heading: 'PaymentX',
    what: 'Full-stack peer-to-peer payment app with secure auth, wallet management, and transaction flows — built end to end.',
    features: ['P2P transfers', 'Wallet management', 'Auth system', 'Transaction history'],
    techstack: ['React.js', 'Node.js', 'MongoDB', 'Tailwind CSS', 'Recoil'],
    link: 'https://payment-app-client.vercel.app/',
    github: 'https://github.com/parthiv011/PaymentApp',
    status: 'live' as const,
  },
];
